# Generated by Django 3.2.12 on 2023-01-07 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('level', models.AutoField(primary_key=True, serialize=False)),
                ('attempt_count', models.IntegerField()),
                ('money_count', models.IntegerField()),
                ('castle', models.CharField(max_length=1000, verbose_name='Замок')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, verbose_name='Имя')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('money', models.IntegerField()),
                ('castle', models.CharField(max_length=1000, verbose_name='Замок')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=3)),
                ('is_completed', models.BooleanField(default=False)),
                ('attempt', models.IntegerField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.map')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.player')),
            ],
        ),
    ]
